services:
  postgres:
    container_name: database_container
    image: postgres:16.3-alpine3.20
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - /postgresql/volume/postgres/data:/database
    ports:
      - 5432:5432
    networks:
      - postgres
  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4:8.8
    environment:
      PGADMIN_DEFAULT_EMAIL: $PGADMIN_DEFAULT_EMAIL
      PGADMIN_DEFAULT_PASSWORD: $PGADMIN_DEFAULT_PASSWORD
      PGADMIN_CONFIG_SERVER_MODE: $PGADMIN_CONFIG_SERVER_MODE
    ports:
      - 5050:80
    restart: unless-stopped
    networks:
      - postgres

networks:
  postgres:
    driver: bridge